[package]
name = "clowder-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
postcard = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
anyhow = { workspace = true }
futures-util = { version = "0.3", features = ["sink"] }
serde_json = "1"
sha2 = "0.11"
hex = "0.4"
